language: php
sudo: false
php:
  - 5.6
  - 5.5
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
services:
  - mongodb
  - elasticsearch
cache:
  directories:
    - vendor
install:
  - composer install --prefer-dist --dev --no-interaction
  # Get fresh tests
  - rm -rf vendor/maslosoft/manganeltest
  - git clone https://github.com/Maslosoft/ManganTest.git vendor/maslosoft/manganeltest
before_script:
  - cd $TRAVIS_BUILD_DIR
script: 
  - bash run-travis
