language: php
php:
  - 5.6
  - 5.5
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
services:
  - mongodb
  - elasticsearch
install:
  - composer install --prefer-dist --dev --no-interaction
  - composer update maslosoft/manganeltest
before_script:
# Wait for mongodb
  - sleep 5
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "extension=mongo.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
script: 
  - run-travis
