language: php
php:
  - 5.6
  - 5.5
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
services:
  - mongodb
  - elasticsearch
install:
  - composer install --prefer-dist --dev --no-interaction
  - composer update maslosoft/manganeltest
before_script:
# Wait for mongodb
  - sleep 5
  - cd $TRAVIS_BUILD_DIR
script: 
  - bash run-travis
