language: php
sudo: false
dist: trusty
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - elasticsearch
    sources:
      - elasticsearch-2.x
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
services:
  - mongodb
  - elasticsearch
cache:
  directories:
    - vendor
install:
  - curl -XGET 'localhost:9200'
  - composer install --prefer-dist --dev --no-interaction
  # Get fresh tests
  - rm -rf vendor/maslosoft/manganeltest
  - git clone https://github.com/Maslosoft/ManganelTest.git vendor/maslosoft/manganeltest
before_script:
  - cd $TRAVIS_BUILD_DIR
script: 
  - bash run-travis
