language: php
sudo: true
dist: bionic
addons:
  apt:
    packages:
      - openjdk-11-jdk-headless
php:
  - 7.4
  - 8.0
  - 8.1
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
services:
  - mongodb
cache:
  directories:
    - vendor
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.16.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.6.16.deb
  - sudo service elasticsearch start
  # Allow ES to start
  - sleep 15
install:
  - mongo --eval "printjson(rs.status())"
  - curl -XGET 'localhost:9200'
  # Ensure that tests project is empty or update might fail
  - rm -rf vendor/maslosoft/mangantest
  # Required for php versions compatibility
  - rm composer.lock
  - composer update
  - composer install --prefer-dist --dev --no-interaction
before_script:
  - cd $TRAVIS_BUILD_DIR
script: 
  - bash run-travis
