language: php
sudo: false
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - elasticsearch
    sources:
      - elasticsearch-2.x
php:
  - 5.6
  - 5.5
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
services:
  - mongodb
  - elasticsearch
cache:
  directories:
    - vendor
env:
  global:
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=2.4.1

install:
  - composer install --prefer-dist --dev --no-interaction
  # Get fresh tests
  - rm -rf vendor/maslosoft/manganeltest
  - git clone https://github.com/Maslosoft/ManganelTest.git vendor/maslosoft/manganeltest
before_script:
  - cd $TRAVIS_BUILD_DIR
script: 
  - bash run-travis
